from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from starlette.middleware.httpsredirect import HTTPSRedirectMiddleware
from starlette.middleware.trustedhost import TrustedHostMiddleware

from app.config import settings
from app.middleware.security import (
    RateLimitMiddleware,
    RateLimitRule,
    SecurityHeadersMiddleware,
)
from app.routes import (
    auth_router,
    billing_router,
    chores_router,
    features_router,
    household_activities_router,
    household_invitations_router,
    households_router,
    notifications_router,
    progress_router,
)


app = FastAPI(
    title=settings.app_name,
    description=(
        "Backend API for the "
        "ChoreFlow SaaS platform."
    ),
    version="0.12.0",
    docs_url=(
        "/docs"
        if settings.docs_enabled
        else None
    ),
    redoc_url=(
        "/redoc"
        if settings.docs_enabled
        else None
    ),
    openapi_url=(
        "/openapi.json"
        if settings.docs_enabled
        else None
    ),
)

# Host-header protection. Add your production API hostname to
# TRUSTED_HOSTS_CSV before deployment.
app.add_middleware(
    TrustedHostMiddleware,
    allowed_hosts=settings.trusted_hosts,
)

# Enable only when your production reverse proxy/platform correctly
# preserves the original HTTPS scheme.
if settings.force_https:
    app.add_middleware(
        HTTPSRedirectMiddleware,
    )

app.add_middleware(
    RateLimitMiddleware,
    rules={
        "/api/v1/auth/login": RateLimitRule(
            limit=settings.auth_login_rate_limit,
            window_seconds=(
                settings.auth_login_rate_window_seconds
            ),
        ),
        "/api/v1/auth/register": RateLimitRule(
            limit=settings.auth_sensitive_rate_limit,
            window_seconds=(
                settings.auth_sensitive_rate_window_seconds
            ),
        ),
        "/api/v1/auth/email-verification/request": RateLimitRule(
            limit=settings.auth_sensitive_rate_limit,
            window_seconds=(
                settings.auth_sensitive_rate_window_seconds
            ),
        ),
        "/api/v1/auth/email-verification/confirm": RateLimitRule(
            limit=(
                settings.auth_sensitive_rate_limit * 3
            ),
            window_seconds=(
                settings.auth_sensitive_rate_window_seconds
            ),
        ),
        "/api/v1/auth/password-reset/request": RateLimitRule(
            limit=settings.auth_sensitive_rate_limit,
            window_seconds=(
                settings.auth_sensitive_rate_window_seconds
            ),
        ),
        "/api/v1/auth/password-reset/confirm": RateLimitRule(
            limit=(
                settings.auth_sensitive_rate_limit * 3
            ),
            window_seconds=(
                settings.auth_sensitive_rate_window_seconds
            ),
        ),
    },
    enabled=settings.rate_limit_enabled,
    trust_proxy_headers=settings.trust_proxy_headers,
)

# ChoreFlow authenticates browser API requests with an explicit Bearer
# Authorization header rather than cross-site cookies, so CORS credentials
# do not need to be enabled.
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_allowed_origins,
    allow_credentials=False,
    allow_methods=[
        "GET",
        "POST",
        "PUT",
        "PATCH",
        "DELETE",
        "OPTIONS",
    ],
    allow_headers=[
        "Accept",
        "Authorization",
        "Content-Type",
        "X-Request-ID",
    ],
    expose_headers=[
        "Retry-After",
        "X-Request-ID",
    ],
    max_age=600,
)

# Added last so it wraps responses generated by the other middleware too.
app.add_middleware(
    SecurityHeadersMiddleware,
    is_production=settings.is_production,
)

app.include_router(auth_router)
app.include_router(chores_router)
app.include_router(billing_router)
app.include_router(features_router)
app.include_router(households_router)
app.include_router(household_invitations_router)
app.include_router(household_activities_router)
app.include_router(progress_router)
app.include_router(notifications_router)


@app.get("/")
def root() -> dict[str, str]:
    return {
        "message": "ChoreFlow API is running",
    }


@app.get("/api/v1/health")
def health_check() -> dict[str, str]:
    return {
        "status": "healthy",
        "service": settings.app_name,
    }
